- hosts: ubuntu_servers
  become: yes
  become_method: sudo
  tasks:
    - name: Install dependencies
      apt:
        name:
        - python3
        - python3-pip
        - python3-setuptools
        state: latest
        update_cache: True
    - name: "Install docker python package"
      pip:
        name: docker
    - name: "Docker prune"
      community.docker.docker_prune:
        containers: yes
        images: yes
        networks: yes
        volumes: yes
        builder_cache: yes
